name: deft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - numpy>=1.23,<2.0
  - scipy>=1.10.0
  - scikit-image>=0.20.0
  - monai>=1.3.0
  - tqdm>=4.64.0
  - pandas>=1.5.0
  - matplotlib>=3.7.0
  - h5py
  - huggingface_hub
  - imageio>=2.25.0
  - pip
  - pip:
      - basicsr
      - lpips>=0.1.4
      - piq>=0.8.0
